/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as authActivateAccountRouteImport } from './routes/(auth)/activate-account'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedEmployeesNewRouteImport } from './routes/_authenticated/employees/new'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedMasterDataAssetTypesRouteImport } from './routes/_authenticated/master-data/asset-types'
import { Route as AuthenticatedMasterDataCostCentersRouteImport } from './routes/_authenticated/master-data/cost-centers'
import { Route as AuthenticatedMasterDataDepartmentsRouteImport } from './routes/_authenticated/master-data/departments'
import { Route as AuthenticatedMasterDataLocationsRouteImport } from './routes/_authenticated/master-data/locations'
import { Route as AuthenticatedMasterDataReasonCodesRouteImport } from './routes/_authenticated/master-data/reason-codes'
import { Route as AuthenticatedMasterDataRepairVendorsRouteImport } from './routes/_authenticated/master-data/repair-vendors'
import { Route as AuthenticatedMasterDataSuppliersRouteImport } from './routes/_authenticated/master-data/suppliers'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const authActivateAccountRoute = authActivateAccountRouteImport.update({
  id: '/(auth)/activate-account',
  path: '/activate-account',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/(auth)/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEmployeesNewRoute =
  AuthenticatedEmployeesNewRouteImport.update({
    id: '/employees/new',
    path: '/employees/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataAssetTypesRoute =
  AuthenticatedMasterDataAssetTypesRouteImport.update({
    id: '/master-data/asset-types',
    path: '/master-data/asset-types',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataCostCentersRoute =
  AuthenticatedMasterDataCostCentersRouteImport.update({
    id: '/master-data/cost-centers',
    path: '/master-data/cost-centers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataDepartmentsRoute =
  AuthenticatedMasterDataDepartmentsRouteImport.update({
    id: '/master-data/departments',
    path: '/master-data/departments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataLocationsRoute =
  AuthenticatedMasterDataLocationsRouteImport.update({
    id: '/master-data/locations',
    path: '/master-data/locations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataReasonCodesRoute =
  AuthenticatedMasterDataReasonCodesRouteImport.update({
    id: '/master-data/reason-codes',
    path: '/master-data/reason-codes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataRepairVendorsRoute =
  AuthenticatedMasterDataRepairVendorsRouteImport.update({
    id: '/master-data/repair-vendors',
    path: '/master-data/repair-vendors',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMasterDataSuppliersRoute =
  AuthenticatedMasterDataSuppliersRouteImport.update({
    id: '/master-data/suppliers',
    path: '/master-data/suppliers',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/activate-account': typeof authActivateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/master-data/asset-types': typeof AuthenticatedMasterDataAssetTypesRoute
  '/master-data/cost-centers': typeof AuthenticatedMasterDataCostCentersRoute
  '/master-data/departments': typeof AuthenticatedMasterDataDepartmentsRoute
  '/master-data/locations': typeof AuthenticatedMasterDataLocationsRoute
  '/master-data/reason-codes': typeof AuthenticatedMasterDataReasonCodesRoute
  '/master-data/repair-vendors': typeof AuthenticatedMasterDataRepairVendorsRoute
  '/master-data/suppliers': typeof AuthenticatedMasterDataSuppliersRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/activate-account': typeof authActivateAccountRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/reset-password': typeof authResetPasswordRoute
  '/sign-in': typeof authSignInRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/master-data/asset-types': typeof AuthenticatedMasterDataAssetTypesRoute
  '/master-data/cost-centers': typeof AuthenticatedMasterDataCostCentersRoute
  '/master-data/departments': typeof AuthenticatedMasterDataDepartmentsRoute
  '/master-data/locations': typeof AuthenticatedMasterDataLocationsRoute
  '/master-data/reason-codes': typeof AuthenticatedMasterDataReasonCodesRoute
  '/master-data/repair-vendors': typeof AuthenticatedMasterDataRepairVendorsRoute
  '/master-data/suppliers': typeof AuthenticatedMasterDataSuppliersRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/activate-account': typeof authActivateAccountRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/employees/new': typeof AuthenticatedEmployeesNewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/master-data/asset-types': typeof AuthenticatedMasterDataAssetTypesRoute
  '/_authenticated/master-data/cost-centers': typeof AuthenticatedMasterDataCostCentersRoute
  '/_authenticated/master-data/departments': typeof AuthenticatedMasterDataDepartmentsRoute
  '/_authenticated/master-data/locations': typeof AuthenticatedMasterDataLocationsRoute
  '/_authenticated/master-data/reason-codes': typeof AuthenticatedMasterDataReasonCodesRoute
  '/_authenticated/master-data/repair-vendors': typeof AuthenticatedMasterDataRepairVendorsRoute
  '/_authenticated/master-data/suppliers': typeof AuthenticatedMasterDataSuppliersRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/settings'
    | '/activate-account'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/employees/new'
    | '/errors/$error'
    | '/master-data/asset-types'
    | '/master-data/cost-centers'
    | '/master-data/departments'
    | '/master-data/locations'
    | '/master-data/reason-codes'
    | '/master-data/repair-vendors'
    | '/master-data/suppliers'
    | '/settings/appearance'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/activate-account'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/employees/new'
    | '/errors/$error'
    | '/master-data/asset-types'
    | '/master-data/cost-centers'
    | '/master-data/departments'
    | '/master-data/locations'
    | '/master-data/reason-codes'
    | '/master-data/repair-vendors'
    | '/master-data/suppliers'
    | '/settings/appearance'
    | '/settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/activate-account'
    | '/(auth)/forgot-password'
    | '/(auth)/reset-password'
    | '/(auth)/sign-in'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/employees/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/master-data/asset-types'
    | '/_authenticated/master-data/cost-centers'
    | '/_authenticated/master-data/departments'
    | '/_authenticated/master-data/locations'
    | '/_authenticated/master-data/reason-codes'
    | '/_authenticated/master-data/repair-vendors'
    | '/_authenticated/master-data/suppliers'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authActivateAccountRoute: typeof authActivateAccountRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSignInRoute: typeof authSignInRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/activate-account': {
      id: '/(auth)/activate-account'
      path: '/activate-account'
      fullPath: '/activate-account'
      preLoaderRoute: typeof authActivateAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees/new': {
      id: '/_authenticated/employees/new'
      path: '/employees/new'
      fullPath: '/employees/new'
      preLoaderRoute: typeof AuthenticatedEmployeesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data/asset-types': {
      id: '/_authenticated/master-data/asset-types'
      path: '/master-data/asset-types'
      fullPath: '/master-data/asset-types'
      preLoaderRoute: typeof AuthenticatedMasterDataAssetTypesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data/cost-centers': {
      id: '/_authenticated/master-data/cost-centers'
      path: '/master-data/cost-centers'
      fullPath: '/master-data/cost-centers'
      preLoaderRoute: typeof AuthenticatedMasterDataCostCentersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data/departments': {
      id: '/_authenticated/master-data/departments'
      path: '/master-data/departments'
      fullPath: '/master-data/departments'
      preLoaderRoute: typeof AuthenticatedMasterDataDepartmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data/locations': {
      id: '/_authenticated/master-data/locations'
      path: '/master-data/locations'
      fullPath: '/master-data/locations'
      preLoaderRoute: typeof AuthenticatedMasterDataLocationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data/reason-codes': {
      id: '/_authenticated/master-data/reason-codes'
      path: '/master-data/reason-codes'
      fullPath: '/master-data/reason-codes'
      preLoaderRoute: typeof AuthenticatedMasterDataReasonCodesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data/repair-vendors': {
      id: '/_authenticated/master-data/repair-vendors'
      path: '/master-data/repair-vendors'
      fullPath: '/master-data/repair-vendors'
      preLoaderRoute: typeof AuthenticatedMasterDataRepairVendorsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/master-data/suppliers': {
      id: '/_authenticated/master-data/suppliers'
      path: '/master-data/suppliers'
      fullPath: '/master-data/suppliers'
      preLoaderRoute: typeof AuthenticatedMasterDataSuppliersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedEmployeesNewRoute: typeof AuthenticatedEmployeesNewRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedMasterDataAssetTypesRoute: typeof AuthenticatedMasterDataAssetTypesRoute
  AuthenticatedMasterDataCostCentersRoute: typeof AuthenticatedMasterDataCostCentersRoute
  AuthenticatedMasterDataDepartmentsRoute: typeof AuthenticatedMasterDataDepartmentsRoute
  AuthenticatedMasterDataLocationsRoute: typeof AuthenticatedMasterDataLocationsRoute
  AuthenticatedMasterDataReasonCodesRoute: typeof AuthenticatedMasterDataReasonCodesRoute
  AuthenticatedMasterDataRepairVendorsRoute: typeof AuthenticatedMasterDataRepairVendorsRoute
  AuthenticatedMasterDataSuppliersRoute: typeof AuthenticatedMasterDataSuppliersRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedEmployeesNewRoute: AuthenticatedEmployeesNewRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedMasterDataAssetTypesRoute:
    AuthenticatedMasterDataAssetTypesRoute,
  AuthenticatedMasterDataCostCentersRoute:
    AuthenticatedMasterDataCostCentersRoute,
  AuthenticatedMasterDataDepartmentsRoute:
    AuthenticatedMasterDataDepartmentsRoute,
  AuthenticatedMasterDataLocationsRoute: AuthenticatedMasterDataLocationsRoute,
  AuthenticatedMasterDataReasonCodesRoute:
    AuthenticatedMasterDataReasonCodesRoute,
  AuthenticatedMasterDataRepairVendorsRoute:
    AuthenticatedMasterDataRepairVendorsRoute,
  AuthenticatedMasterDataSuppliersRoute: AuthenticatedMasterDataSuppliersRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authActivateAccountRoute: authActivateAccountRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSignInRoute: authSignInRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
